In [48]:
import pandas as pd

In [ ]:
df = pd.read_csv("netflix1.csv")
df_backup = df.copy()

df['show_id'] = df['show_id'].str.replace('s', '').astype(int)
df['date_added'] = pd.to_datetime(df['date_added'].str.strip())

In [50]:
new_col_names=[]
for i in df.columns:
    new_col_names.append(i.capitalize())
df.columns=new_col_names

In [51]:
df.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Country', 'Date_added',
       'Release_year', 'Rating', 'Duration', 'Listed_in'],
      dtype='str')

In [52]:
df.drop(columns='Rating')

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,2 Seasons,"International TV Shows, TV Dramas"
8786,8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,3 Seasons,Kids' TV
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,1 Season,Kids' TV
8789,8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,1 Season,Kids' TV

In [53]:
df['Show_id']=df['Show_id'].replace('s','')

In [58]:
df.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Duration,Listed_in
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [61]:
df['Duration_int']=df['Duration'].str.split(' ').str[0].astype(int)
df['Duration_unit']=df['Duration'].str.split(' ').str[1]

In [62]:
df.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Country', 'Date_added',
       'Release_year', 'Rating', 'Duration', 'Listed_in', 'Duration_int',
       'Duration_unit'],
      dtype='str')

In [63]:
df.drop(columns='Duration')

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,"Dramas, Independent Movies, International Movies",125,min
...,...,...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,"International TV Shows, TV Dramas",2,Seasons
8786,8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,Kids' TV,3,Seasons
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,"International TV Shows, Romantic TV Shows, TV ...",1,Season
8788,8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,Kids' TV,1,Season
8789,8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,Kids' TV,1,Season

In [64]:
df.drop_duplicates()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Duration,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min
...,...,...,...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas",2,Seasons
8786,8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,3,Seasons
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",1,Season
8788,8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV,1,Season
8789,8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV,1,Season

In [65]:
df.dropna()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Duration,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min
...,...,...,...,...,...,...,...,...,...,...,...,...
8785,8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas",2,Seasons
8786,8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,3,Seasons
8787,8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",1,Season
8788,8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV,1,Season
8789,8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV,1,Season

In [75]:
df['Show_id'].unique()

array([   1,    3,    6, ..., 8801, 8784, 8786], shape=(8790,))

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Show_id        8790 non-null   int64
 1   Type           8790 non-null   str
 2   Title          8790 non-null   str
 3   Director       8790 non-null   str
 4   Country        8790 non-null   str
 5   Date_added     8790 non-null   datetime64[us]
 6   Release_year   8790 non-null   int64
 7   Rating         8790 non-null   str
 8   Duration       8790 non-null   str
 9   Listed_in      8790 non-null   str
 10  Duration_int   8790 non-null   int64
 11  Duration_unit  8790 non-null   object
dtypes: datetime64[us](1), int64(3), object(1), str(7)
memory usage: 824.2+ KB

In [82]:
df.head(5)

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Duration,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min

In [83]:
df.drop(columns='Duration',inplace=True)

In [84]:
df.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,"Dramas, Independent Movies, International Movies",125,min

In [87]:
df['Type'] = df['Type'].str.strip()
df['Title'] = df['Title'].str.strip()
df['Country'] = df['Country'].str.strip()

In [88]:
df.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Rating,Listed_in,Duration_int,Duration_unit
0,1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,Documentaries,90,min
1,3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",1,Season
2,6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",1,Season
3,14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,"Children & Family Movies, Comedies",91,min
4,8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,"Dramas, Independent Movies, International Movies",125,min

In [99]:
df['Duration_int'].mean()

np.float64(69.9344709897611)

In [91]:
df.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Country', 'Date_added',
       'Release_year', 'Rating', 'Listed_in', 'Duration_int', 'Duration_unit'],
      dtype='str')

In [95]:
df['Duration_unit'].value_counts()

Duration_unit
min        6126
Season     1791
Seasons     873
Name: count, dtype: int64

In [100]:
df.reset_index(drop=True,inplace=True)

In [104]:
df.to_csv("Cleaned Netflix Data",index=False)